/*
 * This file is generated by jOOQ.
 */
package com.shs.codegen.maven.jooq.tables;


import com.shs.codegen.maven.jooq.Indexes;
import com.shs.codegen.maven.jooq.Keys;
import com.shs.codegen.maven.jooq.Public;
import com.shs.codegen.maven.jooq.tables.records.TblUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUser extends TableImpl<TblUserRecord> {

    private static final long serialVersionUID = -1496074897;

    /**
     * The reference instance of <code>public.tbl_user</code>
     */
    public static final TblUser TBL_USER = new TblUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblUserRecord> getRecordType() {
        return TblUserRecord.class;
    }

    /**
     * The column <code>public.tbl_user.id</code>.
     */
    public final TableField<TblUserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('tbl_user_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tbl_user.name</code>.
     */
    public final TableField<TblUserRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.tbl_user</code> table reference
     */
    public TblUser() {
        this(DSL.name("tbl_user"), null);
    }

    /**
     * Create an aliased <code>public.tbl_user</code> table reference
     */
    public TblUser(String alias) {
        this(DSL.name(alias), TBL_USER);
    }

    /**
     * Create an aliased <code>public.tbl_user</code> table reference
     */
    public TblUser(Name alias) {
        this(alias, TBL_USER);
    }

    private TblUser(Name alias, Table<TblUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblUser(Name alias, Table<TblUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TblUser(Table<O> child, ForeignKey<O, TblUserRecord> key) {
        super(child, key, TBL_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TBL_USER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblUserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblUserRecord> getPrimaryKey() {
        return Keys.TBL_USER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblUserRecord>> getKeys() {
        return Arrays.<UniqueKey<TblUserRecord>>asList(Keys.TBL_USER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUser as(String alias) {
        return new TblUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUser as(Name alias) {
        return new TblUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblUser rename(String name) {
        return new TblUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TblUser rename(Name name) {
        return new TblUser(name, null);
    }
}
