/*
 * This file is generated by jOOQ.
 */
package com.shs.codegen.maven.jooq;


import com.shs.codegen.maven.jooq.tables.FlywaySchemaHistory;
import com.shs.codegen.maven.jooq.tables.TblUser;
import com.shs.codegen.maven.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.shs.codegen.maven.jooq.tables.records.TblUserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TblUserRecord, Integer> IDENTITY_TBL_USER = Identities0.IDENTITY_TBL_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<TblUserRecord> TBL_USER_PKEY = UniqueKeys0.TBL_USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TblUserRecord, Integer> IDENTITY_TBL_USER = Internal.createIdentity(TblUser.TBL_USER, TblUser.TBL_USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<TblUserRecord> TBL_USER_PKEY = Internal.createUniqueKey(TblUser.TBL_USER, "tbl_user_pkey", TblUser.TBL_USER.ID);
    }
}
