/*
 * This file is generated by jOOQ.
 */
package com.shs.codegen.maven.jooq;


import com.shs.codegen.maven.jooq.tables.BcUser;
import com.shs.codegen.maven.jooq.tables.BcVisitRequest;
import com.shs.codegen.maven.jooq.tables.FlywaySchemaHistory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bc_user</code>.
     */
    public static final BcUser BC_USER = com.shs.codegen.maven.jooq.tables.BcUser.BC_USER;

    /**
     * The table <code>public.bc_visit_request</code>.
     */
    public static final BcVisitRequest BC_VISIT_REQUEST = com.shs.codegen.maven.jooq.tables.BcVisitRequest.BC_VISIT_REQUEST;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.shs.codegen.maven.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
